### PR TITLE
Translation of Alias and Strings chapter

### PR DESCRIPTION
**Pull request by El-lin**
Based on https://github.com/stonemaster/dlang-tour/pull/384

### CODE REVIEW

**Comment by mihails-strasuns** [comment]
FYI: As @El-lin is doing the editorial/translation per my request, it would be better for someone else to review/merge final state.

Ping @dmi7ry @DmitryOlshansky

**Comment by dmi7ry** [comment]
I will be free in ~two weeks, then I can continue.

**Comment by wilzbach** [comment]
> FYI: As @El-lin is doing the editorial/translation per my request, it would be better for someone else to review/merge final state.

Wow. Maybe we can split the review/merge work with @CyberShadow, @9il or others?

**Comment by 9il** [comment]
LGTM Спасибо @El-lin @dmi7ry

**Comment by wilzbach** [comment]
FYI @El-lin maybe it's a bit motivating to see it online:

http://tour.dlang.io/tour/ru/basics/alias-strings

**Comment by 9il** [comment]
How a user can navigate from http://tour.dlang.io to Russian version?

**Comment by wilzbach** [comment]
> How a user can navigate from http://tour.dlang.io to Russian version?

It's not linked as of now (same for the other [ongoing translations](https://github.com/dlang-tour)), but we will definitely link to the Russian version once it's presentable to a reader (e.g. Welcome + Basics chapters translated).

**Pull request merged**
