### PR TITLE
added `vibe`

### PR DESCRIPTION
**Pull request by dmi7ry**

### CODE REVIEW

**Comment by dmi7ry** [comment]
@wilzbach one more (how I can restart test?)

P.S. That is the last file. All sections done. Then what we need to do for refresh the site?

**Comment by wilzbach** [comment]
> how I can restart test?

Simply go to Travis, login and press restart.

> P.S. That is the last file. All sections done. Then what we need to do for refresh the site?

Awesome! :tada: You​ should make an announcement once it's deployed online.
Unfortunately auto-deploy is broken atm, but @stonemaster plans to fix it within the next days. I will definitely keep you posted. Sorry about the inconveniences :/

**Comment by radcapricorn** [comment]
@dmi7ry @wilzbach Hey, it's up! 🎉

**Comment by wilzbach** [comment]
> Unfortunately auto-deploy is broken atm, but @stonemaster plans to fix it within the next days. I will definitely keep you posted. Sorry about the inconveniences :/

-> https://tour.dlang.org/tour/ru/welcome/welcome-to-d

@dmi7ry @radcapricorn (and others) I think you have deserved an announcement at the NG!!
Do you want to announce it yourself?

**Comment by wilzbach** [comment]
> @dmi7ry @wilzbach Hey, it's up! :tada:

Yes. It's also packed with a couple of new goodies ("Format", "Export current example", ...) ;-)
I had to manually deploy it (see https://github.com/dlang-tour/spanish/issues/9), so until the auto-deploy issues are finally resolved, feel free to ping me for a new manual deploy.

**Comment by radcapricorn** [comment]
> Yes. It's also packed with a couple of new goodies ("Format", "Export current example", ...) ;-)

Ack, those buttons! Why haven't we translated those buttons? :)

> Do you want to announce it yourself?

I could do that.

**Comment by wilzbach** [comment]
> Ack, those buttons! Why haven't we translated those buttons? :)

Yep it depends on this PR: https://github.com/dlang-tour/core/pull/510
If you agree with this way to allow language-based translations, I would be happy to merge it, s.t. you can add translations for these four buttons and we can deploy a fully translated version ;-)

**Comment by radcapricorn** [comment]
@dmi7ry @wilzbach [the announcement](http://forum.dlang.org/thread/llpkyxdysehxsuqfkuqc@forum.dlang.org).

**Pull request merged**
