### PR TITLE
Translation of Array chapter

### PR DESCRIPTION
**Pull request by El-lin**
Editing based on https://github.com/stonemaster/dlang-tour/pull/384

### CODE REVIEW

**Comment by wilzbach** [comment]
Random Russian reviewer roulette: Maybe @bubnenkoff could act as a second pair of eyes on the translation?

**Comment by bubnenkoff** [comment]
Yes, I can. I see that a lot of translation already done. 
Am I right understand that I need pull repo, do fix/translation and that do push request? I have not good knowledge of git.

**Comment by wilzbach** [comment]
> Yes, I can. I see that a lot of translation already done. 
> Am I right understand that I need pull repo, do fix/translation and that do push request? I have not good knowledge of git.

Oh no, as I don't speak russian, it would be very kind if you could look over the text and see if there are any typos or other language issues.
If you find something, the easiest way is to comment on that line.

**Comment by mihails-strasuns** [comment]
No, no need to pull anything, simply comment on this PR if there is anything you think should be fixed. Or LGTM and I will merge.

**Comment by 9il** [comment]
@El-lin could you please rebase the PR, hope this will fix travis

**Comment by El-lin** [comment]
> could you please rebase the PR, hope this will fix travis

Yep, green now.

**Pull request merged**
