### PR TITLE
Translation of Install D locally chapter

### PR DESCRIPTION
**Pull request by El-lin**
Based on https://github.com/stonemaster/dlang-tour/pull/384

### CODE REVIEW

**Comment by 9il** [comment]
I am interesting if we can provide a universal link instead of specific version.

**Comment by mihails-strasuns** [comment]
CC @MartinNowak - is there a way link latest version?

**Comment by wilzbach** [comment]
I guess the best way for now is to use the global variable `latest-release`, see e.g. https://github.com/dlang-tour/english/edit/master/welcome/install-d-locally.md

Not perfect, but only one place to update the version for all languages.

**Comment by 9il** [comment]
Thanks @wilzbach

**Pull request merged**
