### PR TITLE
Translation of Foreach chapter

### PR DESCRIPTION
**Pull request by El-lin**
Based on https://github.com/stonemaster/dlang-tour/pull/384

### CODE REVIEW

**Comment by El-lin** [comment]
Can somebody explain me what has failed here? As I'm not a very experienced github user.

**Comment by wilzbach** [comment]
> Can somebody explain me what has failed here? As I'm not a very experienced github user.

Just click on the "Details" link of the Travis report.
In this case it's not your fault, I will fix it soon. Sorry :/

**Comment by wilzbach** [comment]
> In this case it's not your fault, I will fix it soon. Sorry :/

Everything should be normal again - sorry about that.

**Comment by El-lin** [comment]
> Everything should be normal again - sorry about that.

Ok, thank you.

**Review by 9il — APPROVED** [review]

**Pull request merged**
